version: '3.1'

services:

    db:
        image: postgres:10
        restart: always
        environment:
            POSTGRES_USER: dost
            POSTGRES_PASSWORD: changeme
            POSTGRES_DB: tododb

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080